import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { prisma } from "./db";
import { emailOTP } from "better-auth/plugins"
import { resend } from "./resend";
export const auth = betterAuth({ //this creates the auth configuration file for the server side 
    database: prismaAdapter(prisma, { 
        provider: "postgresql", // or "mysql", "postgresql", ...etc
    }),
  //  emailAndPassword: { 
  //   enabled: true, 
  // }, 
  socialProviders: { 
    github: { 
      clientId: process.env.AUTH_GITHUB_CLIENT_ID as string, 
      clientSecret: process.env.AUTH_GITHUB_CLIENT_SECRET as string, 
    }, 
    //TODO: implement google login 
  },  
  plugins: [
        emailOTP({ 
            async sendVerificationOTP({ email, otp, type }) { //email: the user email //otp is generated by the better-auth //type  
             await resend.emails.send({
                from:"MerebLearning <onboarding@resend.dev>",
                to: [email],
                subject: "Mereb Learning - Verify your email",
                html: `<p>Your OTP is  <strong>${otp}</strong></p>`
              })
            }
        }) 
    ]


});